### ISSUE TITLE
Exception for negative field

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#514] opened 2016-08-22 08:16 UTC
```
    Task exception was never retrieved
future: <Task finished coro=<_async_search_direct_connections() done, defined at sakia\gui\identities_tab.py:144> exception=TypeError("unsupported operand type(s) for -: 'int' and 'NoneType'",)>

    ----
    Traceback (most recent call last):

  File "asyncio\tasks.py", line 239, in _step

  File "sakia\gui\identities_tab.py", line 159, in _async_search_direct_connections

  File "sakia\core\registry\identity.py", line 454, in unique_valid_certifiers_of

  File "sakia\core\registry\identity.py", line 418, in _unique_valid

  File "sakia\core\community.py", line 268, in certification_expired

TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```

**Comment by Insoleet** [comment] 2016-08-22 10:12
Bug probably caused by a Duniter Error which does not return anything if the error is not "Block not found" : https://github.com/duniter/sakia/blob/master/src/sakia/core/community.py#L227

**Comment by M5oul** [comment] 2016-08-22 14:41
Seems duplicate of https://github.com/duniter/sakia/issues/503.

**Closed** 2017-01-14 15:40 UTC
Labels: bug
