### ISSUE TITLE
transaction message encryption

### ISSUE THREAD

**Issue by Nartagnan** [duniter/sakia#722] opened 2017-07-04 05:37 UTC
(I put it here, but it concerns all Duniter clients)

Could Sakia propose an option to encrypt the transaction message with the receiver pubkey ? (and to decrypt it of course).
It is normal that it is not the default, but could be a useful option.

**Comment by Insoleet** [comment] 2017-07-06 11:01
Duplicate of https://github.com/duniter/sakia/issues/358

**Closed by Insoleet** 2017-07-06 11:01 UTC
