### ISSUE TITLE
problem with key CSjgcGguFJe3ghBBjjGyNVdvC3rqtXE7rSxUaLzjxBhR

### ISSUE THREAD

**Issue by librelois** [duniter/sakia#696] opened 2017-05-19 20:09 UTC
With 0.32.0RC2 
When i add a pubkey connection to CSjgcGguFJe3ghBBjjGyNVdvC3rqtXE7rSxUaLzjxBhR, i have this error : 

Task exception was never retrieved
	future: <Task finished coro=<ConnectionConfigController.process() done, defined at sakia/gui/dialogs/connection_cfg/controller.py:109> exception=NotAnAttrsClassError("<class 'NoneType'> is not an attrs-decorated class.",)>

	    ----
	    Traceback (most recent call last):

	  File "asyncio/tasks.py", line 239, in _step

	  File "sakia/gui/dialogs/connection_cfg/controller.py", line 203, in process

	  File "sakia/gui/dialogs/connection_cfg/model.py", line 113, in initialize_transactions

	  File "sakia/data/processors/transactions.py", line 147, in initialize_transactions

	  File "sakia/data/repositories/transactions.py", line 18, in insert

	  File "site-packages/attr/_funcs.py", line 98, in astuple

	  File "site-packages/attr/_make.py", line 543, in fields

	attr.exceptions.NotAnAttrsClassError: <class 'NoneType'> is not an attrs-decorated class.

**Comment by Insoleet** [comment] 2017-05-22 06:45
Okay it's really really weird. Yesterday I was able to reproduce the bug, but today it is able to parse the transaction history as intended ?! Can you try again ?

**Comment by Insoleet** [comment] 2017-05-22 06:53
Okay got it ! Weird bug, it seems to come from Duniter...

The pubkey is : 
```  
CSjgcGguFJe3ghBBjjGyNVdvC3rqtXE7rSxUaLzjxBhR
```

The output contains : 
```
CSjgcGguFje3ghBBjjGyNVdvC3rqtXE7rSxUaLzjxBhR
```

Look at the 10th character : the output contains a `j` whereas the pubkey contains a `J`.

We are looking for the wrong pubkey actually ! The bug is the following : 

 - Duniter matches the pubkey with a lower `j`  when we are looking for an upper `J`. It should probably not match. ( cc @c-geek )
 - Sakia fails at parsing because the outputs do not match the pubkey and crashes. This will be fixed in next release
 - Finally, we should probably implement CRC pubkey for such things not to happen. I wonder how we got the wrong pubkey in the first place... Which client displayed this pubkey ?

**Comment by c-geek** [comment] 2017-05-22 10:38
Indeed I could reproduce on SQLite that the uppercased `J`: 

```sql
select *
from s_index
where conditions like 'SIG(CSjgcGguFJe3ghBBjjGyNVdvC3rqtXE7rSxUaLzjxBhR)'
```

Returns 3 rows matching the lowercased `j`. The solution is to use `=` comparison:

```sql
select * 
from s_index 
where conditions = 'SIG(CSjgcGguFJe3ghBBjjGyNVdvC3rqtXE7rSxUaLzjxBhR)'
```

In this situation I got 0 rows with `J` but 3 rows with `j`, which is the expected result.

I've added duniter/duniter#985 on my side.

**Comment by c-geek** [comment] 2017-05-23 14:25
Finally fixed on duniter with a more general solution: execute the following statement on database opening.

```sql
PRAGMA case_sensitive_like=ON;
```

**Closed** 2017-05-23 17:09 UTC
Labels: bug
