### ISSUE TITLE
Display each endpoint as a different peer under Network tab

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#533] opened 2016-09-14 13:25 UTC
Now that having multiple peers per pubkey on the network is possible, it would be nice if Sakia could display these peers as independant peers under the Network tab.

For example this peer:

```json
{
  "version": 2,
  "currency": "test_net",
  "endpoints": [
    "BASIC_MERKLED_API cgeek.fr 88.174.120.187 2a01:e35:8ae7:8bb0:b468:a0c:a607:379f 9330",
    "BASIC_MERKLED_API win-dev.cgeek.fr 88.174.120.187 9333"
  ],
  "block": "38706-0000157811BF9B2A6A3C708C34F27A24FAD4ABB62B71D1309758E6D967040750",
  "signature": "g6ZcBv+HtIBBlP9jBP37CLMpj41NR8F6Snng/z6hwOrQWfowG+cIbHw30+vTcJJlaWzETucNdyGiSFFNlM9fAw==",
  "pubkey": "HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk"
}
```

is currently displayed as only 1 peer, which is `cgeek.fr`. It would be cool to also see `win-dev.cgeek.fr` independently.

**Comment by M5oul** [comment] 2016-09-14 13:28
Duplicate of https://github.com/duniter/sakia/issues/265

**Comment by M5oul** [comment] 2016-09-14 13:31
Migrated on other ticket.

**Closed by M5oul** 2016-09-14 13:31 UTC
Labels: duplicate
