### ISSUE TITLE
Cannot save revocation document

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#717] opened 2017-06-22 15:19 UTC
When I try to save my revocation document, I got questionned about my salt/password, and then a popup opens to "Save the file" and Sakia crashes:

```
/opt/sakia/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libproxy.so.1)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so

(sakia:5391): Gtk-WARNING **: Invalid input string

(sakia:5391): Gtk-WARNING **: Invalid input string
Erreur de segmentation (core dumped)
```

OS: Ubuntu 16.04 + Gnome

**Comment by Insoleet** [comment] 2017-06-23 06:27
I will have to crowdfund in Ğ1 the integration of vagrant builds of Sakia ! The travis builds are getting more annoying everyday...

**Comment by Insoleet** [comment] 2017-06-24 10:14
Duplicate of https://github.com/duniter/sakia/issues/712

**Closed by Insoleet** 2017-06-24 10:14 UTC
Labels: bug
