### ISSUE TITLE
Error bug report

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#610] opened 2017-02-18 12:50 UTC
With 0.30.7:
```bash
DEBUG:node:connect_peers:Received a peer : J78bP
ERROR:root:Task exception was never retrieved
future: <Task finished coro=<NetworkService.discovery_loop() done, defined at sakia/services/network.py:203> exception=RuntimeError('coroutine raised StopIteration',)>
Traceback (most recent call last):
  File "sakia/services/network.py", line 226, in discovery_loop
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "asyncio/tasks.py", line 239, in _step
RuntimeError: coroutine raised StopIteration
DEBUG:node:connect_peers:Received a peer : BmDso
```

**Comment by Insoleet** [comment] 2017-04-29 10:30
Duplicate of https://github.com/duniter/sakia/issues/612

**Closed by Insoleet** 2017-04-29 10:30 UTC
Labels: bug, network
