### ISSUE TITLE
Warnings 0.30.10

### ISSUE THREAD

**Issue by galuel** [duniter/sakia#606] opened 2017-02-17 08:12 UTC
Ils étaient déjà là en 0.30.9 : 

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:88:7: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:93:7: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:98:11: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:105:11: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:112:7: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:117:11: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:124:7: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:129:7: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:134:11: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:140:11: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:146:7: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:151:20: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:296:7: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:301:7: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:306:11: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:313:11: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:320:7: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:326:20: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:332:7: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:337:7: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:342:11: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:348:11: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:354:7: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:359:20: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:448:30: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:458:30: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:468:30: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:478:30: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:498:22: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:503:22: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:508:22: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:513:22: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:155:8: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:163:8: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:189:8: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:199:8: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:703:13: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:776:19: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:796:16: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1256:36: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1260:36: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1264:29: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1465:28: No property named '-gtk-icon-transform'

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1525:18: 'outline-radius' is not a valid property name

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1686:45: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1704:45: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1747:25: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1755:25: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1776:25: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1784:25: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1800:25: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1818:25: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2027:19: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2045:19: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2164:2: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: unity.css:126:28: No property named '-gtk-icon-transform'

(sakia:4128): Gtk-WARNING **: Theme parsing error: nautilus.css:40:16: 'outline-radius' is not a valid property name

(sakia:4128): Gtk-WARNING **: Theme parsing error: gnome-panel.css:92:20: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gnome-panel.css:98:20: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gnome-panel.css:104:20: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: gnome-terminal.css:10:41: Missing name of pseudo-class

(sakia:4128): Gtk-WARNING **: Theme parsing error: unity-greeter.css:72:28: No property named '-gtk-icon-transform'

(sakia:4128): Gtk-WARNING **: Theme parsing error: calendar.css:9:18: 'outline-radius' is not a valid property name

**Comment by Insoleet** [comment] 2017-02-17 09:00
Duplicate of #608

**Closed by Insoleet** 2017-02-17 09:00 UTC
Labels: bug
