### ISSUE TITLE
Can't launch Sakia without pyenv

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#561] opened 2017-01-18 12:00 UTC
On `master` branch 0.30:
After reinstalling all python dependencies and removing `.config/sakia`, I get this bug:
```bash
/usr/bin/python2: No module named PyQt5
/home/moul/projects/sakia_dev/res/i18n/langs-1484740705.qrc >> /home/moul/projects/sakia_dev/src/i18n_rc.py
DEBUG:meta:prepare:Initializing meta database
DEBUG:meta:upgrade_database:Begin upgrade of database...
DEBUG:meta:upgrade_database:End upgrade of database...
DEBUG:network:add_connector:HnFcS connected
ERROR:root:An unhandled exception occured
Traceback (most recent call last):
  File "src/sakia/main.py", line 93, in <module>
    app = Application.startup(sys.argv, sakia, loop)
  File "/home/moul/projects/sakia_dev/src/sakia/app.py", line 85, in startup
    app.switch_language()
  File "/home/moul/projects/sakia_dev/src/sakia/app.py", line 163, in switch_language
    QCoreApplication.removeTranslator(self._translator)
TypeError: removeTranslator(QTranslator): argument 1 has unexpected type 'Attribute'
ERROR:root:Task was destroyed but it is pending!
task: <Task pending coro=<get_last_version() running at /home/moul/projects/sakia_dev/src/sakia/app.py:183>>
sys:1: RuntimeWarning: coroutine 'get_last_version' was never awaited
ERROR:root:Task was destroyed but it is pending!
task: <Task pending coro=<NetworkService.discover_network() running at /home/moul/projects/sakia_dev/src/sakia/services/network.py:173>>
sys:1: RuntimeWarning: coroutine 'NetworkService.discover_network' was never awaited
```

**Comment by Insoleet** [comment] 2017-01-18 13:15
Interesting bug, thanks for the report !

**Comment by Insoleet** [comment] 2017-01-18 19:21
I can't reproduce this bug. I see the line `/usr/bin/python2: No module named PyQt5` at the beginning of your logs, did you make any mistake ?

**Comment by M5oul** [comment] 2017-01-19 03:28
I already had this logs before and it was working on Sakia 0.20.
That could be the issue.
If I remember well, this error log appears when my computer migrated from Fedora 24 to 25.
Here is [python-qt5 package used](https://apps.fedoraproject.org/packages/python-qt5).

**Comment by Insoleet** [comment] 2017-01-19 12:12
I think you should really consider using a pyenv environment. Especially since you can use `pip install PyQt5` now :)

**Comment by M5oul** [comment] 2017-01-19 17:18
Ok, a pyenv should solve the issue.
I will see that later.

**Comment by Insoleet** [comment] 2017-01-25 07:18
Did you encounter this bug since then ?

**Comment by M5oul** [comment] 2017-01-25 07:41
Yep, I reproduce it again on a non-pyenv environement.

**Comment by Insoleet** [comment] 2017-01-25 11:46
Can you try using python3 instead of python2 ?

**Comment by M5oul** [comment] 2017-01-25 19:35
I am running Python 3:

```bash
        python3 gen_resources.py
        python3 gen_translations.py
        python3 src/sakia/main.py -d
```

I don't know why python2 is used.

**Comment by Insoleet** [comment] 2017-01-25 19:46
When is the error with python2 displayed ?

**Comment by M5oul** [comment] 2017-01-25 19:53
at the end of `python3 gen_resources.py` command:
```bash
python3 gen_resources.py
/home/moul/projects/sakia_git/src/sakia/gui/preferences.ui >> /home/moul/projects/sakia_git/src/sakia/gui/preferences_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/sub/password_input/password_input.ui >> /home/moul/projects/sakia_git/src/sakia/gui/sub/password_input/password_input_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/sub/search_user/search_user.ui >> /home/moul/projects/sakia_git/src/sakia/gui/sub/search_user/search_user_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/sub/user_information/user_information.ui >> /home/moul/projects/sakia_git/src/sakia/gui/sub/user_information/user_information_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/main_window/mainwindow.ui >> /home/moul/projects/sakia_git/src/sakia/gui/main_window/mainwindow_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/main_window/toolbar/about.ui >> /home/moul/projects/sakia_git/src/sakia/gui/main_window/toolbar/about_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/main_window/toolbar/toolbar.ui >> /home/moul/projects/sakia_git/src/sakia/gui/main_window/toolbar/toolbar_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/dialogs/certification/certification.ui >> /home/moul/projects/sakia_git/src/sakia/gui/dialogs/certification/certification_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/dialogs/transfer/transfer.ui >> /home/moul/projects/sakia_git/src/sakia/gui/dialogs/transfer/transfer_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/dialogs/revocation/revocation.ui >> /home/moul/projects/sakia_git/src/sakia/gui/dialogs/revocation/revocation_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/dialogs/connection_cfg/connection_cfg.ui >> /home/moul/projects/sakia_git/src/sakia/gui/dialogs/connection_cfg/connection_cfg_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/navigation/navigation.ui >> /home/moul/projects/sakia_git/src/sakia/gui/navigation/navigation_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/navigation/homescreen/homescreen.ui >> /home/moul/projects/sakia_git/src/sakia/gui/navigation/homescreen/homescreen_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/navigation/identities/identities.ui >> /home/moul/projects/sakia_git/src/sakia/gui/navigation/identities/identities_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/navigation/graphs/wot/wot_tab.ui >> /home/moul/projects/sakia_git/src/sakia/gui/navigation/graphs/wot/wot_tab_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/navigation/informations/informations.ui >> /home/moul/projects/sakia_git/src/sakia/gui/navigation/informations/informations_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/navigation/network/network.ui >> /home/moul/projects/sakia_git/src/sakia/gui/navigation/network/network_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/navigation/txhistory/txhistory.ui >> /home/moul/projects/sakia_git/src/sakia/gui/navigation/txhistory/txhistory_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/widgets/toast.ui >> /home/moul/projects/sakia_git/src/sakia/gui/widgets/toast_uic.py
/home/moul/projects/sakia_git/res/icons/icons.qrc >> /home/moul/projects/sakia_git/src/icons_rc.py
/usr/bin/python2: No module named PyQt5
```

**Comment by Insoleet** [comment] 2017-01-25 20:08
It looks like gen_resources is trying to use `pyrcc5` from python2. ?

**Comment by M5oul** [comment] 2017-01-26 05:50
yep, that's strange.

**Comment by M5oul** [comment] 2017-01-26 05:58
With last git version, I have that, with unfinished translation generation:
```bash
./run_sakia.sh git
/home/moul/projects/sakia_git/src/sakia/gui/preferences.ui >> /home/moul/projects/sakia_git/src/sakia/gui/preferences_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/sub/password_input/password_input.ui >> /home/moul/projects/sakia_git/src/sakia/gui/sub/password_input/password_input_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/sub/search_user/search_user.ui >> /home/moul/projects/sakia_git/src/sakia/gui/sub/search_user/search_user_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/sub/user_information/user_information.ui >> /home/moul/projects/sakia_git/src/sakia/gui/sub/user_information/user_information_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/main_window/mainwindow.ui >> /home/moul/projects/sakia_git/src/sakia/gui/main_window/mainwindow_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/main_window/toolbar/about.ui >> /home/moul/projects/sakia_git/src/sakia/gui/main_window/toolbar/about_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/main_window/toolbar/toolbar.ui >> /home/moul/projects/sakia_git/src/sakia/gui/main_window/toolbar/toolbar_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/dialogs/certification/certification.ui >> /home/moul/projects/sakia_git/src/sakia/gui/dialogs/certification/certification_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/dialogs/transfer/transfer.ui >> /home/moul/projects/sakia_git/src/sakia/gui/dialogs/transfer/transfer_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/dialogs/revocation/revocation.ui >> /home/moul/projects/sakia_git/src/sakia/gui/dialogs/revocation/revocation_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/dialogs/connection_cfg/connection_cfg.ui >> /home/moul/projects/sakia_git/src/sakia/gui/dialogs/connection_cfg/connection_cfg_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/navigation/navigation.ui >> /home/moul/projects/sakia_git/src/sakia/gui/navigation/navigation_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/navigation/homescreen/homescreen.ui >> /home/moul/projects/sakia_git/src/sakia/gui/navigation/homescreen/homescreen_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/navigation/identities/identities.ui >> /home/moul/projects/sakia_git/src/sakia/gui/navigation/identities/identities_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/navigation/graphs/wot/wot_tab.ui >> /home/moul/projects/sakia_git/src/sakia/gui/navigation/graphs/wot/wot_tab_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/navigation/informations/informations.ui >> /home/moul/projects/sakia_git/src/sakia/gui/navigation/informations/informations_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/navigation/network/network.ui >> /home/moul/projects/sakia_git/src/sakia/gui/navigation/network/network_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/navigation/txhistory/txhistory.ui >> /home/moul/projects/sakia_git/src/sakia/gui/navigation/txhistory/txhistory_uic.py
/home/moul/projects/sakia_git/src/sakia/gui/widgets/toast.ui >> /home/moul/projects/sakia_git/src/sakia/gui/widgets/toast_uic.py
/home/moul/projects/sakia_git/res/icons/icons.qrc >> /home/moul/projects/sakia_git/src/icons_rc.py
/usr/bin/python2: No module named PyQt5
/home/moul/projects/sakia_git/res/i18n/ts/fr.ts
/home/moul/projects/sakia_git/res/i18n/ts/de.ts
/home/moul/projects/sakia_git/res/i18n/ts/cs.ts
/home/moul/projects/sakia_git/res/i18n/ts/it.ts
/home/moul/projects/sakia_git/res/i18n/ts/pt.ts
/home/moul/projects/sakia_git/res/i18n/ts/es.ts
/home/moul/projects/sakia_git/res/i18n/ts/pl.ts
/home/moul/projects/sakia_git/res/i18n/ts/ru.ts
Updating '/home/moul/projects/sakia_git/res/i18n/qm/fr.qm'...
    Generated 123 translation(s) (40 finished and 83 unfinished)
    Ignored 97 untranslated source text(s)
/home/moul/projects/sakia_git/res/i18n/ts/fr.ts >> /home/moul/projects/sakia_git/res/i18n/qm/fr.qm
Updating '/home/moul/projects/sakia_git/res/i18n/qm/de.qm'...
    Generated 99 translation(s) (22 finished and 77 unfinished)
    Ignored 121 untranslated source text(s)
/home/moul/projects/sakia_git/res/i18n/ts/de.ts >> /home/moul/projects/sakia_git/res/i18n/qm/de.qm
Updating '/home/moul/projects/sakia_git/res/i18n/qm/cs.qm'...
    Generated 123 translation(s) (40 finished and 83 unfinished)
    Ignored 97 untranslated source text(s)
/home/moul/projects/sakia_git/res/i18n/ts/cs.ts >> /home/moul/projects/sakia_git/res/i18n/qm/cs.qm
Updating '/home/moul/projects/sakia_git/res/i18n/qm/it.qm'...
    Generated 104 translation(s) (29 finished and 75 unfinished)
    Ignored 116 untranslated source text(s)
/home/moul/projects/sakia_git/res/i18n/ts/it.ts >> /home/moul/projects/sakia_git/res/i18n/qm/it.qm
Updating '/home/moul/projects/sakia_git/res/i18n/qm/pt.qm'...
    Generated 105 translation(s) (23 finished and 82 unfinished)
    Ignored 115 untranslated source text(s)
/home/moul/projects/sakia_git/res/i18n/ts/pt.ts >> /home/moul/projects/sakia_git/res/i18n/qm/pt.qm
Updating '/home/moul/projects/sakia_git/res/i18n/qm/es.qm'...
    Generated 97 translation(s) (27 finished and 70 unfinished)
    Ignored 123 untranslated source text(s)
/home/moul/projects/sakia_git/res/i18n/ts/es.ts >> /home/moul/projects/sakia_git/res/i18n/qm/es.qm
Updating '/home/moul/projects/sakia_git/res/i18n/qm/pl.qm'...
    Generated 77 translation(s) (15 finished and 62 unfinished)
    Ignored 143 untranslated source text(s)
/home/moul/projects/sakia_git/res/i18n/ts/pl.ts >> /home/moul/projects/sakia_git/res/i18n/qm/pl.qm
Updating '/home/moul/projects/sakia_git/res/i18n/qm/ru.qm'...
    Generated 55 translation(s) (7 finished and 48 unfinished)
    Ignored 165 untranslated source text(s)
/home/moul/projects/sakia_git/res/i18n/ts/ru.ts >> /home/moul/projects/sakia_git/res/i18n/qm/ru.qm
<RCC>
      <qresource prefix="i18n">
<file alias="fr">qm/fr.qm</file>
<file alias="de">qm/de.qm</file>
<file alias="cs">qm/cs.qm</file>
<file alias="it">qm/it.qm</file>
<file alias="pt">qm/pt.qm</file>
<file alias="es">qm/es.qm</file>
<file alias="pl">qm/pl.qm</file>
<file alias="ru">qm/ru.qm</file>
      </qresource>
    </RCC>
    
/usr/bin/python2: No module named PyQt5
/home/moul/projects/sakia_git/res/i18n/langs-1485410160.qrc >> /home/moul/projects/sakia_git/src/i18n_rc.py
DEBUG:meta:prepare:Initializing meta database
DEBUG:meta:upgrade_database:Begin upgrade of database...
DEBUG:meta:upgrade_database:Upgrading to version 0...
DEBUG:meta:create_all_tables:Initialiazing all databases
DEBUG:meta:upgrade_database:End upgrade of database...
DEBUG:network:add_connector:C4orq connected
ERROR:root:An unhandled exception occured
Traceback (most recent call last):
  File "src/sakia/main.py", line 93, in <module>
    app = Application.startup(sys.argv, sakia, loop)
  File "/home/moul/projects/sakia_git/src/sakia/app.py", line 89, in startup
    app.switch_language()
  File "/home/moul/projects/sakia_git/src/sakia/app.py", line 168, in switch_language
    QCoreApplication.removeTranslator(self._translator)
TypeError: removeTranslator(QTranslator): argument 1 has unexpected type 'Attribute'
ERROR:root:Task was destroyed but it is pending!
task: <Task pending coro=<get_last_version() running at /home/moul/projects/sakia_git/src/sakia/app.py:190>>
sys:1: RuntimeWarning: coroutine 'get_last_version' was never awaited
ERROR:root:Task was destroyed but it is pending!
task: <Task pending coro=<NetworkService.discover_network() running at /home/moul/projects/sakia_git/src/sakia/services/network.py:173>>
sys:1: RuntimeWarning: coroutine 'NetworkService.discover_network' was never awaite
```

**Comment by Insoleet** [comment] 2017-01-26 09:25
What does `which pyrcc5` returns ?

**Comment by M5oul** [comment] 2017-01-27 06:35
```bash
which pyrcc5
/usr/bin/pyrcc5

usr/bin/pyrcc5 -h
/usr/bin/python2: No module named PyQt5
```

**Comment by Insoleet** [comment] 2017-01-27 07:10
Well your pyrcc5 is for python2 not python3. It comes with your pyqt5 installation.

**Comment by M5oul** [comment] 2017-01-27 07:17
Here is [the ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1411160) about this problem.

**Comment by Insoleet** [comment] 2017-01-27 07:22
Ok. I close this one then.

**Closed by Insoleet** 2017-01-27 07:22 UTC
Labels: bug

**Comment by M5oul** [comment] 2017-02-01 06:38
`/usr/bin/python2: No module named PyQt5` have been fixed.

But I still have:
```bash
DEBUG:network:add_connector:qxJ39 connected
ERROR:root:An unhandled exception occured
Traceback (most recent call last):
  File "src/sakia/main.py", line 93, in <module>
    app = Application.startup(sys.argv, sakia, loop)
  File "/home/moul/projects/sakia_git/src/sakia/app.py", line 90, in startup
    app.switch_language()
  File "/home/moul/projects/sakia_git/src/sakia/app.py", line 169, in switch_language
    QCoreApplication.removeTranslator(self._translator)
TypeError: removeTranslator(QTranslator): argument 1 has unexpected type 'Attribute'
ERROR:root:Task was destroyed but it is pending!
task: <Task pending coro=<get_last_version() running at /home/moul/projects/sakia_git/src/sakia/app.py:191>>
sys:1: RuntimeWarning: coroutine 'get_last_version' was never awaited
ERROR:root:Task was destroyed but it is pending!
task: <Task pending coro=<NetworkService.discover_network() running at /home/moul/projects/sakia_git/src/sakia/services/network.py:173>>
sys:1: RuntimeWarning: coroutine 'NetworkService.discover_network' was never awaited
```

**Comment by M5oul** [comment] 2017-02-20 08:13
Ok, I succeed to make it works inside a pyenv \o/

**Comment by Insoleet** [comment] 2017-02-20 09:20
👍
