### ISSUE TITLE
Network: current block is not refreshed

### ISSUE THREAD

**Issue by M5oul** [duniter/sakia#368] opened 2016-02-09 12:35 UTC
Sakia is stucked on block 49733 while nodes say current block is more than [49867](https://moul.re/ucoin/blockchain/current).

**Comment by Insoleet** [comment] 2016-02-09 13:07
What do you mean by "stucked on block" ?

The nodes are not refreshed ?

Which version do you use, 0.12dev6 or less ?

**Comment by M5oul** [comment] 2016-02-09 21:12
Nodes on network tab are displaying block 49733.
I use 0.12dev6.

**Comment by M5oul** [comment] 2016-02-14 13:34
It happen again:
![capture d ecran de 2016-02-14 14-29-08](https://cloud.githubusercontent.com/assets/4758871/13033945/c424b4da-d327-11e5-885a-d120305ee900.png)
Current block of all nodes is 50148.

**Comment by M5oul** [comment] 2016-02-14 14:42
I needed to restart Sakia to get current block displayed on all node.

**Comment by Insoleet** [comment] 2016-02-14 17:31
It is not happening here.

Can you share a part of your log containing the following text : `DEBUG:node:connect_current_block:Received a block` 

Thanks !

**Comment by M5oul** [comment] 2016-02-14 20:10
I can't easily find what you want.
I let you found in [logs](https://moul.re/jirafeau/f.php?h=0_VhFXyY&d=1).

**Comment by Insoleet** [comment] 2016-02-14 21:33
Your logs are too big, you should clean the file before reproducing the problem...

**Comment by M5oul** [comment] 2016-02-14 22:40
I can't reproduce it.

**Comment by Insoleet** [comment] 2016-02-18 07:59
I checked your logs, it's weird since I can see many logs with`Latest block changed : 50163`  `Latest block changed : 50164` `Latest block changed : 50165`... It looks like in the core, new blocks were correctly found.

**Comment by M5oul** [comment] 2016-02-18 13:05
It's a rare and minor bug. You can close it.

**Comment by Insoleet** [comment] 2016-02-18 13:45
Ok. I think we will be able to release then.

**Comment by M5oul** [comment] 2016-02-24 22:05
I reproduced it.
It happen with a connection interruption. It break websocket connection.
The websocket connection need to be reestablished.

**Comment by Insoleet** [comment] 2016-03-14 12:33
Bug with aiohttp : https://github.com/KeepSafe/aiohttp/issues/827

**Comment by Insoleet** [comment] 2016-03-16 08:14
Could you try again and see if it's still buggy ?

**Comment by Insoleet** [comment] 2016-03-16 17:31
Should be fixed with latest heartbeats mechanism.

**Comment by M5oul** [comment] 2016-03-16 18:24
I can't test it.
I migrate my dev env to Sakia 0.20. I don't really wan't to build all Qt for a dev env for 0.12. 
I am using a build of Sakia 0.12 I've made.

**Comment by Insoleet** [comment] 2016-03-16 18:28
You don't need to rebuild Qt to develop for sakia 0.12 ;) Just run `pip install --upgrade -r requirements.txt` to get sakia 0.12 dependencies, it's pretty fast !

**Comment by M5oul** [comment] 2016-03-16 18:58
Ok, on `dev0121` branch, after `pip install --upgrade -r requirements.txt`, I get this error, even with a cleared cache:
```fish
Traceback (most recent call last):
  File "src/sakia/main.py", line 21, in <module>
    from sakia.gui.mainwindow import MainWindow
  File "/home/moul/projects/sakia/build/src/sakia/gui/mainwindow.py", line 16, in <module>
    from .process_cfg_account import ProcessConfigureAccount
  File "/home/moul/projects/sakia/build/src/sakia/gui/process_cfg_account.py", line 10, in <module>
    from ..gui.process_cfg_community import ProcessConfigureCommunity
  File "/home/moul/projects/sakia/build/src/sakia/gui/process_cfg_community.py", line 18, in <module>
    from ..core import Community
  File "/home/moul/projects/sakia/build/src/sakia/core/__init__.py", line 1, in <module>
    from .community import Community
  File "/home/moul/projects/sakia/build/src/sakia/core/community.py", line 17, in <module>
    from .net.network import Network
  File "/home/moul/projects/sakia/build/src/sakia/core/net/__init__.py", line 1, in <module>
    from .node import Node
  File "/home/moul/projects/sakia/build/src/sakia/core/net/node.py", line 8, in <module>
    from ucoinpy.documents import Block, BlockId, MalformedDocumentError
```

If it's an other bug, we should migrate this answer to an other ticket.

**Comment by Insoleet** [comment] 2016-03-16 19:07
It's missing the error :)

**Comment by M5oul** [comment] 2016-03-16 20:55
In fact, I updated it.

**Comment by M5oul** [comment] 2016-03-19 14:34
Ok, I succeed going to 0.12. I will try.

**Comment by M5oul** [comment] 2016-08-10 13:11
I can still reproduce it.
I was gone open a new ticket and I remembered I already opened it :wink: 
Here is its content:

When I let open Sakia a long time on network tab, nodes are no more refreshed,
You could see Ğaluel node which have 22 blocks ahead of other nodes.
If I restart Sakia, all nodes have same current block as Ğaluel one.
![capture du 2016-08-10 15-05-33](https://cloud.githubusercontent.com/assets/4758871/17554612/0024950c-5f0c-11e6-930e-a80820deb858.png)

**Comment by Insoleet** [comment] 2016-08-10 14:08
The maintainer of aiohttp is currently fixing a lot of bugs and refactoring the code websocket module : 
https://github.com/KeepSafe/aiohttp/issues?utf8=%E2%9C%93&q=websocket

Let's see if it gets better in future versions.

**Closed** 2017-01-14 15:53 UTC
Labels: bug, enhancement, network
