### ISSUE TITLE
    Exception in callback SSLProtocol._process_write_backlog()

### ISSUE THREAD

**Issue by mcl12345** [duniter/sakia#777] opened 2018-01-31 15:23 UTC
Exception in callback SSLProtocol._process_write_backlog()
    handle: <Handle SSLProtocol._process_write_backlog()>

    ----
    Traceback (most recent call last):

     File "asyncio\sslproto.py", line 639, in _process_write_backlog

     AttributeError: 'NoneType' object has no attribute 'do_handshake'

   During handling of the above exception, another exception occurred:

   Traceback (most recent call last):

      File "asyncio\events.py", line 127, in _run

     File "asyncio\sslproto.py", line 665, in _process_write_backlog

     File "asyncio\sslproto.py", line 579, in _on_handshake_complete

     AttributeError: 'NoneType' object has no attribute 'ssl_object'

**Comment by roco** [comment] 2018-02-19 21:57
same message here.
i just removed 0.32.2 and installed 0.32.9

**Comment by Insoleet** [comment] 2018-02-20 08:30
Related to https://github.com/aio-libs/aiohttp/issues/2546

**Comment by Insoleet** [comment] 2018-02-25 10:25
I can no more reproduce this error since I fixed ClientSession leaks. It seems fixed in next release.

**Closed by Insoleet** 2018-02-25 10:25 UTC
