### ISSUE TITLE
Cannot refresh history with 0.20.8

### ISSUE THREAD

**Issue by c-geek** [duniter/sakia#527] opened 2016-08-25 06:09 UTC
Sakia is stuck at 99% while parsing transaction history, and I finally get this error message:

```
    Task exception was never retrieved
future: <Task finished coro=<TxHistory._refresh() done, defined at sakia\core\txhistory.py:244> exception=AttributeError("'str' object has no attribute 'version'",)>

    ----
    Traceback (most recent call last):

  File "asyncio\tasks.py", line 239, in _step

  File "sakia\core\txhistory.py", line 279, in _refresh

  File "sakia\core\txhistory.py", line 204, in _parse_block

  File "sakia\core\txhistory.py", line 109, in _get_block_doc

  File "site-packages\duniterpy\documents\block.py", line 412, in from_signed_raw

  File "site-packages\duniterpy\documents\block.py", line 208, in __init__

  File "site-packages\duniterpy\documents\block.py", line 208, in <listcomp>

AttributeError: 'str' object has no attribute 'version'
```

And also at the same time:

```
    Exception in callback Task._wakeup(<Future finished result=None>)
handle: <Handle Task._wakeup(<Future finished result=None>)>

    ----
    Traceback (most recent call last):

  File "asyncio\events.py", line 125, in _run

  File "asyncio\tasks.py", line 307, in _wakeup

  File "asyncio\tasks.py", line 291, in _step

KeyError: <QSelectorEventLoop running=True closed=False debug=False>
```

I tried to completely remove my .config/sakia folder, but I still get the same result.

**Comment by Insoleet** [comment] 2016-08-25 06:27
Check version 0.20.9 please :) Duplicate of https://github.com/duniter/sakia/issues/525

**Closed by Insoleet** 2016-08-25 06:27 UTC
